import Head from 'next/head'
import { Button } from 'components/Button'

export default function Home() {
  return (
    <div className="container mx-auto px-4">
      <Head>
        <title>Next.js monorepo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Next.js monorepo example with reusable components and Tailwind CSS
        </h1>

        <Button>Button from components</Button>

        <button className="bg-pink-700 text-white p-2 rounded-lg hover:opacity-90">Local button</button>
      </main>

      <footer></footer>
    </div>
  )
}
